### ISSUE TITLE
Install script mod

### ISSUE THREAD

**Issue by DABtester** [DABodr/ODRinstaller#3]
Hi there,

I'm running Raspberry buster, and I found two possible issue's with the "Install_script_ODR+Config.sh" script:

"sudo apt-get -y install vlc-plugins-base" cannot be found in the repository.
Changed it to "sudo apt-get -y install vlc-plugin-base"

Also

"supervisior mplayer2" cannot be found in the repository.
Changed it to "supervisor mplayer"

**Comment by DABodr** [comment]
Yes all fixed now :) mplayer was deleted from script, not use here
